/**
 * Artifact created event
 */

export interface ArtifactCreatedEvent {
  readonly type: 'artifact-created';
  readonly artifactId: string;
  readonly conversationId: string;
  readonly messageId: string;
  readonly artifactType: string;
  readonly title: string;
  readonly timestamp: Date;
  readonly metadata: {
    readonly size: number;
    readonly language?: string;
    readonly version: number;
    readonly tags: string[];
    readonly autoGenerated: boolean;
  };
}

export function createArtifactCreatedEvent(
  artifactId: string,
  conversationId: string,
  messageId: string,
  artifactType: string,
  title: string,
  size: number,
  version = 1,
  language?: string,
  tags: string[] = [],
  autoGenerated = true
): ArtifactCreatedEvent {
  return {
    type: 'artifact-created',
    artifactId,
    conversationId,
    messageId,
    artifactType,
    title,
    timestamp: new Date(),
    metadata: {
      size,
      language,
      version,
      tags,
      autoGenerated
    }
  };
}
